# Generated by Django 4.0.6 on 2022-07-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='Bio',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
