# Generated by Django 3.2.14 on 2022-07-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
