# Generated by Django 3.2.14 on 2022-07-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='pic',
            field=models.ImageField(blank=True, default='defaultpic.png', null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='pic_cover',
            field=models.ImageField(blank=True, default='defaultpic.png', null=True, upload_to='img'),
        ),
    ]
