# Generated by Django 4.0.6 on 2022-07-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='iconId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
