# Generated by Django 3.2.14 on 2022-07-31 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_shares_sharedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentsgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentdate', models.DateTimeField(auto_now_add=True)),
                ('commentcontent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.TextField()),
                ('group_pic', models.ImageField(blank=True, null=True, upload_to='img')),
                ('About_group', models.TextField()),
                ('members', models.ManyToManyField(blank=True, related_name='members', to='Home.Useraccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='Home.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='MemberRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timesstamp', models.DateTimeField(auto_now_add=True)),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_sender_req', to='Home.groups')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_sender_req', to='Home.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Postlikegroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PostsGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postdate', models.DateTimeField(auto_now_add=True)),
                ('postcontent', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='img')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.groups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.useraccount')),
            ],
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.AddField(
            model_name='postlikegroup',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.postsgroups'),
        ),
        migrations.AddField(
            model_name='postlikegroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.useraccount'),
        ),
        migrations.AddField(
            model_name='commentsgroup',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='Home.postsgroups'),
        ),
        migrations.AddField(
            model_name='commentsgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.useraccount'),
        ),
    ]
