# Generated by Django 4.0.6 on 2022-07-31 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_commentsgroup_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.useraccount'),
        ),
    ]
