# Generated by Django 4.0.6 on 2022-07-30 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_postlike_iconid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.TextField()),
                ('group_pic', models.ImageField(blank=True, null=True, upload_to='img')),
                ('About_group', models.TextField()),
                ('members', models.ManyToManyField(blank=True, related_name='members', to='Home.useraccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='Home.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='MemberRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timesstamp', models.DateTimeField(auto_now_add=True)),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_sender_req', to='Home.groups')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_sender_req', to='Home.useraccount')),
            ],
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
