# Generated by Django 3.2.14 on 2022-07-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_friendrequest_frienlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
