# Generated by Django 4.0.6 on 2022-08-03 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_postsgroups_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostlikeShares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconId', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.shares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsShares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentdate', models.DateTimeField(auto_now_add=True)),
                ('commentcontent', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='Home.shares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.useraccount')),
            ],
        ),
    ]
