# Generated by Django 3.2.14 on 2022-07-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20220728_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='pic',
            field=models.ImageField(blank=True, default='img/defaultpic.png', null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='pic_cover',
            field=models.ImageField(blank=True, default='img/defaultpic.png', null=True, upload_to='img'),
        ),
    ]
