# Generated by Django 4.0.6 on 2022-07-23 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_useraccount_bio'),
        ('Home', '0003_alter_comments_post'),
    ]

    operations = [
    ]
