# Generated by Django 3.2.14 on 2022-07-30 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_postlike_iconid'),
        ('Home', '0003_alter_posts_user'),
    ]

    operations = [
    ]
