# Generated by Django 4.0.6 on 2022-08-03 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_postlikeshares_commentsshares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsshares',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments_shares', to='Home.shares'),
        ),
    ]
