# Generated by Django 4.0.6 on 2022-08-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20220801_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='isactive',
            field=models.BooleanField(default='True'),
        ),
    ]
