# Generated by Django 3.2.14 on 2022-07-21 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_posts_postdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_photos', to='Home.posts'),
        ),
    ]
