# Generated by Django 4.0.6 on 2022-08-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_useraccount_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='isactive',
            field=models.BooleanField(default=False),
        ),
    ]
