# Generated by Django 4.0.6 on 2022-07-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_merge_0002_useraccount_bio_0003_alter_comments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
