# Generated by Django 4.0.6 on 2022-07-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_posts_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='like',
        ),
        migrations.AddField(
            model_name='postlike',
            name='islike',
            field=models.BooleanField(default=True),
        ),
    ]
