# Generated by Django 4.0.6 on 2022-07-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_story_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='timesstamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
