# Generated by Django 4.0.6 on 2022-07-26 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_remove_postlike_islike_posts_islike'),
        ('Home', '0007_story_timesstamp'),
    ]

    operations = [
    ]
