# Generated by Django 3.2.14 on 2022-07-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0003_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
