# Generated by Django 3.2.14 on 2022-07-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0005_auto_20220714_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
